from django.urls import path
from . import views

urlpatterns = [
    path("", views.login_view, name="login"),
    path("login/", views.login_view, name="login-page"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("members/", views.members_view, name="members"),
    path("plans/", views.plans_view, name="plans"),
    path("subscriptions/", views.subscriptions_view, name="subscriptions"),
    path("pricing/", views.pricing_view, name="pricing"),
    path("payments/", views.payments_view, name="payments"),
    path("invoices/", views.invoices_view, name="invoices"),
    path("renewals/", views.renewals_view, name="renewals"),
    path("refunds/", views.refunds_view, name="refunds"),
    path("attendance/", views.attendance_view, name="attendance"),
    path("expenses/", views.expenses_view, name="expenses"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("reports/", views.reports_view, name="reports"),
    path("users/", views.users_view, name="users"),
    path("settings/", views.settings_view, name="settings"),
    path("members/detail/", views.member_detail_view, name="member-detail"),
    path("members/add/", views.member_add_view, name="member-add"),
    path("services/", views.services_view, name="services"),
    path("plans/create/", views.plan_create_view, name="plan-create"),
    path("plans/custom/", views.plan_custom_view, name="plan-custom"),
    path("subscriptions/detail/", views.subscription_detail_view, name="subscription-detail"),
    path("subscriptions/create/", views.subscription_create_view, name="subscription-create"),
    path("payments/detail/", views.payment_detail_view, name="payment-detail"),
    path("refunds/detail/", views.refund_detail_view, name="refund-detail"),
    path("refunds/history/", views.refund_history_view, name="refund-history"),
    path("statement/", views.statement_view, name="statement"),
    path("attendance/checkin/", views.attendance_checkin_view, name="attendance-checkin"),
    path("expenses/add/", views.expense_add_view, name="expense-add"),
    path("users/add/", views.user_add_view, name="user-add"),
    path("reports/generate/", views.reports_generate_view, name="reports-generate"),
    path("receipts/custom/", views.receipt_custom_view, name="receipt-custom"),
]
