from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_bill_to'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS receipts (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                receipt_no varchar(50) NOT NULL UNIQUE,
                bill_to varchar(255),
                member_id integer REFERENCES members(id) ON DELETE SET NULL,
                invoice_id integer,
                payment_id integer,
                description text,
                subtotal numeric(12,2) NOT NULL DEFAULT 0,
                discount_type varchar(10) NOT NULL DEFAULT 'flat',
                discount numeric(12,2) NOT NULL DEFAULT 0,
                tax_rate numeric(6,2) NOT NULL DEFAULT 0,
                tax_amount numeric(12,2) NOT NULL DEFAULT 0,
                total numeric(12,2) NOT NULL DEFAULT 0,
                method varchar(50) NOT NULL DEFAULT 'cash',
                notes text,
                paid_date date NOT NULL DEFAULT CURRENT_DATE,
                created_at timestamptz NOT NULL DEFAULT now()
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS receipts;",
        ),
    ]