# Generated by Django 6.1 on 2026-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationsetting_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Setting',
                'verbose_name_plural': 'Financial Settings',
                'db_table': 'financial',
            },
        ),
    ]
