# Generated by Django 6.1 on 2026-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_financialsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='Admin', max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='settings/avatars/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['pk'],
            },
        ),
    ]
